### ISSUE TITLE
gpiocdev > 0.6.0 don't compile with aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by jsnnerve** [warthog618/gpiocdev-rs#17]
Hi,

I cannot compile gpiocdev 0.6.1 and newer for aarch64-unknown-linux-musl, it works fine with 0.6.0 and older.

14.24    Compiling async-stream v0.3.5
14.30 error[E0308]: mismatched types
14.30    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:119:13
14.30     |
14.30 117 |         match libc::ioctl(
14.30     |               ----------- arguments to this function are incorrect
14.30 118 |             cf.as_raw_fd(),
14.30 119 |             ior!(Ioctl::GetChipInfo, ChipInfo),
14.30     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.30     |
14.30 note: function defined here
14.30    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.30     |
14.30 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.30     |            ^^^^^
14.30 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.30     |
14.30 25  |         (ioctl_sys::ior!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.30     |         +                                                                                    +++++++++++++++++++++
14.30
14.31 error[E0308]: mismatched types
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:135:48
14.31     |
14.31 135 |     match unsafe { libc::ioctl(cf.as_raw_fd(), iorw!(Ioctl::UnwatchLineInfo, u32), &offset) } {
14.31     |                    -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.31     |                    |
14.31     |                    arguments to this function are incorrect
14.31     |
14.31 note: function defined here
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.31     |
14.31 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.31     |            ^^^^^
14.31 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.31     |
14.31 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.31     |         +                                                                                     +++++++++++++++++++++
14.31
14.31 error[E0308]: mismatched types
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:172:48
14.31     |
14.31 172 |     match unsafe { libc::ioctl(lf.as_raw_fd(), iorw!(Ioctl::GetLineValues, LineValues), lv) } {
14.31     |                    -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.31     |                    |
14.31     |                    arguments to this function are incorrect
14.31     |
14.31 note: function defined here
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.31     |
14.31 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.31     |            ^^^^^
14.31 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.31     |
14.31 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.31     |         +                                                                                     +++++++++++++++++++++
14.31
14.31 error[E0308]: mismatched types
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:187:48
14.31     |
14.31 187 |     match unsafe { libc::ioctl(lf.as_raw_fd(), iorw!(Ioctl::SetLineValues, LineValues), lv) } {
14.31     |                    -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.31     |                    |
14.31     |                    arguments to this function are incorrect
14.31     |
14.31 note: function defined here
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.31     |
14.31 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.31     |            ^^^^^
14.31 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.31    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.31     |
14.31 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.31     |         +                                                                                     +++++++++++++++++++++
14.32
14.32 error[E0308]: mismatched types
14.32    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:430:43
14.32     |
14.32 430 |         match libc::ioctl(lf.as_raw_fd(), iorw!(Ioctl::SetLineConfig, LineConfig), &lc) {
14.32     |               -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.32     |               |
14.32     |               arguments to this function are incorrect
14.32     |
14.32 note: function defined here
14.32    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.32     |
14.32 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.32     |            ^^^^^
14.32 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.32    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.32     |
14.32 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.32     |         +                                                                                     +++++++++++++++++++++
14.32
14.32    Compiling libz-sys v1.1.16
14.32 error[E0308]: mismatched types
14.32    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:483:43
14.32     |
14.32 483 |         match libc::ioctl(cf.as_raw_fd(), iorw!(Ioctl::GetLine, LineRequest), &lr) {
14.32     |               -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.33     |               |
14.33     |               arguments to this function are incorrect
14.33     |
14.33 note: function defined here
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.33     |
14.33 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.33     |            ^^^^^
14.33 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.33     |
14.33 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.33     |         +                                                                                     +++++++++++++++++++++
14.33
14.33 error[E0308]: mismatched types
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:574:48
14.33     |
14.33 574 |     match unsafe { libc::ioctl(cf.as_raw_fd(), iorw!(Ioctl::GetLineInfo, LineInfo), &li) } {
14.33     |                    -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.33     |                    |
14.33     |                    arguments to this function are incorrect
14.33     |
14.33 note: function defined here
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.33     |
14.33 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.33     |            ^^^^^
14.33 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.33     |
14.33 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.33     |         +                                                                                     +++++++++++++++++++++
14.33
14.33 error[E0308]: mismatched types
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/v2.rs:596:48
14.33     |
14.33 596 |     match unsafe { libc::ioctl(cf.as_raw_fd(), iorw!(Ioctl::WatchLineInfo, LineInfo), &li) } {
14.33     |                    -----------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u64`
14.33     |                    |
14.33     |                    arguments to this function are incorrect
14.33     |
14.33 note: function defined here
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/linux_like/linux/musl/mod.rs:850:12
14.33     |
14.33 850 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
14.33     |            ^^^^^
14.33 help: you can convert a `u64` to an `i32` and panic if the converted value doesn't fit
14.33    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gpiocdev-uapi-0.6.1/src/common.rs:32:9
14.33     |
14.33 32  |         (ioctl_sys::iorw!(IOCTL_MAGIC, $nr, mem::size_of::<$dty>()) as ::std::os::raw::c_ulong).try_into().unwrap()
14.33     |         +                                                                                     +++++++++++++++++++++
14.33

**Comment by warthog618** [comment]
My first guess is that the switch from **nix** to **ioctl-sys** in 85f0b3f75c56416166a5f62c4a55e7f841544597 doesn't work for musl, though it does work for gnu.   Any chance you could confirm that - I don't normally build for musl, so I would need to go look into setting up a build environment.

**Comment by jsnnerve** [comment]
Yes, version 0.7 compiles fine with aarch64-unknown-linux-gnu

**Comment by warthog618** [comment]
Yeah, I know - I can and do build for aarch64 gnu, but not musl.
I meant can you confirm that the repo builds for musl at commit bfa6280e389ba0676a7ea34c0e17428fed38bc62 (the one before the nix change), but not after the nix change.  Basically a `git bisect`, but taking a good guess what the offending commit is.

Alternatively, what is the easiest way to build for aarch64 musl?  I have a Raspberry Pi 4 handy if that helps.

**Comment by jsnnerve** [comment]
[commit](https://github.com/warthog618/gpiocdev-rs/commit/bfa6280e389ba0676a7ea34c0e17428fed38bc62) fails to build for musl

**Comment by warthog618** [comment]
Can you do a `git bisect` to identify the commit that is the first bad one?

**Comment by jsnnerve** [comment]
Yes, I can do that next week

**Comment by jsnnerve** [comment]
Ok, that was easier than expected, I did this:

git bisect start lib-v0.6.0 lib-v0.6.1
git bisect start lib-v0.6.1 lib-v0.6.0
git bisect run cargo check --target x86_64-unknown-linux-musl

and got:

85f0b3f75c56416166a5f62c4a55e7f841544597 is the first bad commit
commit 85f0b3f75c56416166a5f62c4a55e7f841544597
Author: Kent Gibson <warthog618@gmail.com>
Date:   Sun Sep 24 17:30:25 2023 +0800

    switch ioctl code generation from nix to ioctl-sys

 uapi/Cargo.toml    |  2 +-
 uapi/src/common.rs | 22 ++++++++++++-----
 uapi/src/v1.rs     | 68 ++++++----------------------------------------------
 uapi/src/v2.rs     | 70 +++++-------------------------------------------------
 4 files changed, 30 insertions(+), 132 deletions(-)

**Comment by warthog618** [comment]
Good - it is the one I expected.  Easiest fix is probably to revert that change, so switch back to **nix**.  I was trying to minimize dependencies, and **ioctl-sys** has fewer, but if it is also less portable then **nix** is better.

And I just found I can just install aarch64-unknown-linux-musl as a target with `rustup`, so I can chase it up without having to bother you.

**Comment by warthog618** [comment]
I've pushed a commit b190b94c7195d294c2c54035c55e8c1d1b4c437b that fixes the musl build for me on aarch64, arm and x86_64.
Can you check that works for you?

**Comment by warthog618** [comment]
Included in release uapi-v0.6.2.
